# Generated by Django 6.0.1 on 2026-02-02 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('experience_min', models.IntegerField()),
                ('experience_max', models.IntegerField()),
                ('job_type', models.CharField(choices=[('FT', 'Full-time'), ('IN', 'Internship'), ('CT', 'Contract')], max_length=2)),
                ('description', models.TextField()),
                ('skills', models.CharField(max_length=255)),
                ('deadline', models.DateField()),
                ('tag_fresher', models.BooleanField(default=False)),
                ('visibility', models.CharField(choices=[('FREE', 'Free'), ('PRO', 'Pro')], default='FREE', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('PUBLISHED', 'Published'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
