# Generated by Django 6.0.1 on 2026-02-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_job_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('FT', 'Full-time'), ('IN', 'Internship'), ('CT', 'Contract')], max_length=2),
        ),
    ]
