# Generated by Django 6.0.1 on 2026-02-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_job_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='visibility',
            field=models.CharField(choices=[('FREE', 'Free'), ('PRO', 'Pro'), ('PROPLUS', 'ProPLUS')], default='FREE', max_length=10),
        ),
    ]
