# Generated by Django 6.0.1 on 2026-02-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='training_images/'),
        ),
    ]
