# Generated by Django 6.0.1 on 2026-02-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_trainingenquiry_message_enquirymessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='course_timing',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='mentor_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='mentor_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
