# Generated by Django 6.0.1 on 2026-02-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_enrollment_certificate_enrollment_course_timing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='training_link',
            field=models.URLField(blank=True),
        ),
    ]
