# Generated by Django 6.0.1 on 2026-02-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('highlight_text', models.CharField(blank=True, max_length=100)),
                ('subtitle', models.TextField()),
                ('background_image', models.ImageField(upload_to='home/hero/')),
                ('overlay_opacity', models.FloatField(default=0.4, help_text='0 = no overlay, 1 = fully dark')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Homepage Hero Section',
                'verbose_name_plural': 'Homepage Hero Section',
            },
        ),
    ]
