# Generated by Django 6.0.1 on 2026-02-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_homehero'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homehero',
            options={},
        ),
        migrations.AddField(
            model_name='homehero',
            name='theme',
            field=models.CharField(choices=[('dark', 'Dark Text (for light image)'), ('light', 'Light Text (for dark image)')], default='light', max_length=10),
        ),
        migrations.AlterField(
            model_name='homehero',
            name='overlay_opacity',
            field=models.FloatField(default=0.35),
        ),
    ]
