# Generated by Django 6.0.1 on 2026-02-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_homehero_options_homehero_theme_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homehero',
            options={'verbose_name': 'Homepage Hero Section', 'verbose_name_plural': 'Homepage Hero Section'},
        ),
        migrations.RemoveField(
            model_name='homehero',
            name='theme',
        ),
        migrations.AlterField(
            model_name='homehero',
            name='overlay_opacity',
            field=models.FloatField(default=0.4, help_text='0 = no overlay, 1 = fully dark'),
        ),
    ]
