# Generated by Django 6.0.1 on 2026-02-06 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_homehero_options_remove_homehero_theme_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('link_type', models.CharField(choices=[('enquiry', 'Career Enquiry Page'), ('jobs', 'Jobs Page'), ('training', 'Training Page')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
