# Generated by Django 6.0.1 on 2026-02-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_sitestatistic'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField(blank=True)),
                ('button_text', models.CharField(default='Create Free Account', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Homepage Bottom CTA',
                'verbose_name_plural': 'Homepage Bottom CTA',
            },
        ),
    ]
