# Generated by Django 6.0.1 on 2026-02-06 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_featuresection_homefeature_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homefeature',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='core.featuresection'),
        ),
    ]
