# Generated by Django 6.0.1 on 2026-02-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_trainingcompletion_trainingmodule_moduleprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='My Company', max_length=200)),
                ('signatory_name', models.CharField(default='Authorized Signatory', max_length=150)),
                ('background', models.ImageField(blank=True, null=True, upload_to='certificate_assets/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='certificate_assets/')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='certificate_assets/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
