# Generated by Django 6.0.1 on 2026-02-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_certificatedesign'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='placement_support',
            field=models.BooleanField(default=False),
        ),
    ]
