# Generated by Django 6.0.1 on 2026-02-04 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_completed_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
