# Generated by Django 6.0.1 on 2026-02-04 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_profile_completed_email_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_completed_email_sent',
        ),
    ]
