# Generated by Django 6.0.1 on 2026-02-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_mobile_number_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='completion_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
