# Generated by Django 6.0.1 on 2026-02-07 05:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_completion_email_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subscription_type',
        ),
        migrations.AddField(
            model_name='user',
            name='ai_requests_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='job_applications_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='mentor_sessions_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='plan',
            field=models.CharField(choices=[('FREE', 'Free'), ('PRO', 'Pro'), ('PRO_PLUS', 'Pro Plus')], default='FREE', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='plan_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='plan_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='plan_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('TRIAL', 'Trial')], default='TRIAL', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='usage_reset_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
