# Generated by Django 6.0.1 on 2026-02-07 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_user_subscription_type_user_ai_requests_used_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_type', models.CharField(choices=[('BASIC', 'Pro Suggestion'), ('ADVANCED', 'Pro Plus Optimization')], max_length=20)),
                ('feedback', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_reviews', to='accounts.profile')),
            ],
        ),
    ]
