# Generated by Django 6.0.1 on 2026-02-07 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_resumereview'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resumereview',
            unique_together={('profile', 'review_type')},
        ),
    ]
