# Generated by Django 6.0.1 on 2026-02-07 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_resumereview_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResumeReview',
        ),
    ]
