# Generated by Django 6.0.1 on 2026-02-07 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_delete_resumereview'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_type', models.CharField(choices=[('BASIC', 'Pro Suggestion'), ('ADVANCED', 'Pro Plus Optimization')], max_length=20)),
                ('feedback', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_reviews', to='accounts.profile')),
            ],
            options={
                'unique_together': {('profile', 'review_type')},
            },
        ),
    ]
