# Generated by Django 6.0.1 on 2026-02-10 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_dashboardcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedJobsCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Saved Jobs', max_length=100)),
                ('icon', models.ImageField(upload_to='dashboard_icons/')),
            ],
        ),
        migrations.DeleteModel(
            name='DashboardCard',
        ),
    ]
