# Generated by Django 6.0.1 on 2026-02-10 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_savedjobscard_delete_dashboardcard'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SavedJobsCard',
            new_name='DashboardCard',
        ),
    ]
