# Generated by Django 6.0.1 on 2026-02-10 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_rename_savedjobscard_dashboardcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardcard',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='dashboard_icons/'),
        ),
    ]
