# Generated by Django 6.0.1 on 2026-02-10 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_dashboardcard_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardcard',
            name='key',
            field=models.CharField(choices=[('saved', 'Saved Jobs'), ('applications', 'Applications')], default='saved', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dashboardcard',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
