# Generated by Django 6.0.1 on 2026-02-10 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_dashboardcard_key_alter_dashboardcard_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DashboardCard',
        ),
    ]
