# Generated by Django 6.0.1 on 2026-02-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_delete_dashboardcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='experience',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
