# Generated by Django 6.0.1 on 2026-02-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_subscriptionpricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='purchased_plan',
            field=models.CharField(blank=True, choices=[('FREE', 'Free'), ('PRO', 'Pro'), ('PRO_PLUS', 'Pro Plus')], max_length=20, null=True),
        ),
    ]
