# Generated by Django 6.0.1 on 2026-02-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_delete_staffprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_admin_alert',
            field=models.BooleanField(default=False),
        ),
    ]
