# Generated by Django 6.0.1 on 2026-02-13 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_notification_is_admin_alert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='training',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.DeleteModel(
            name='SubscriptionPricing',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
