# Generated by Django 6.0.1 on 2026-02-13 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_remove_payment_training_remove_payment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('SYSTEM', 'System'), ('TRAINER', 'Trainer'), ('CONSULTANT', 'Consultant'), ('CANDIDATE', 'Candidate'), ('PAYMENT', 'Payment')], default='SYSTEM', max_length=20),
        ),
    ]
