# Generated by Django 6.0.1 on 2026-02-13 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_notification_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='type',
        ),
    ]
