# Generated by Django 6.0.1 on 2026-02-13 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_remove_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('GENERAL', 'General'), ('TRAINER', 'Trainer'), ('JOB', 'Job'), ('SYSTEM', 'System')], default='GENERAL', max_length=20),
        ),
    ]
