# Generated by Django 6.0.1 on 2026-02-13 19:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock_interview', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewfeedback',
            name='communication',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='problem_solving',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='technical',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mockinterview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mockinterview',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mockinterview',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interviewfeedback',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mockinterview',
            name='consultant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainer_mock_interviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mockinterview',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
