# Generated by Django 6.0.1 on 2026-02-13 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0002_consultantsession_feedback_consultantsession_trainer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultantsession',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='consultantsession',
            name='trainer',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True, 'is_superuser': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_consultations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='consultantsession',
            index=models.Index(fields=['status', 'scheduled_at'], name='consultatio_status_95a325_idx'),
        ),
        migrations.AddIndex(
            model_name='consultantsession',
            index=models.Index(fields=['trainer', 'status'], name='consultatio_trainer_7ea6ca_idx'),
        ),
    ]
